# Generated by Django 5.0.7 on 2024-07-25 03:25

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_eventpage_organizer_eventpage_capacity_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='tags',
        ),
        migrations.AddField(
            model_name='eventpage',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
